version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: dream-vacation-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dream-vacation-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dream-vacation-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - COUNTRIES_API_BASE_URL=${COUNTRIES_API_BASE_URL}
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - dream-vacation-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dream-vacation-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    environment:
      - PORT=3000
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - NODE_OPTIONS=--openssl-legacy-provider
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - dream-vacation-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  mysql_data:

networks:
  dream-vacation-network:
    driver: bridge