name: Deploy Dream Vacation App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-backend ./backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-backend

    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-frontend ./frontend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-frontend

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.EC2_PATH }}
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-backend
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-frontend
          docker-compose down
          docker-compose up -d
